---
###############################################################################################
## REGISTRY
###############################################################################################
- block:
  - name: Create directory for registry keys
    file:
      path: "/etc/docker/certs.d/{{front_hostname}}:5000/"
      state: directory

  - name: Create registry certificates
    include: create_registry_certificates.yml
    when: docker_registry_certificates == "generate"

  - name: Obtain the registry certificates using SCP 
    include: ssh_get_registry_certificates.yml
    when: docker_registry_certificates == "ssh"

  - name: Copy {{front_hostname}}.cert file
    copy:
      remote_src: True
      dest: "/etc/docker/certs.d/{{front_hostname}}:5000/{{front_hostname}}.cert"
      src: "/opt/docker_registry/certs/{{front_hostname}}.cert"

  - name: Copy {{front_hostname}}.key file
    copy:
      remote_src: True
      dest: "/etc/docker/certs.d/{{front_hostname}}:5000/{{front_hostname}}.key"
      src: "/opt/docker_registry/certs/{{front_hostname}}.key"

  - name: Copy ca.crt file
    copy:
      remote_src: True
      dest: "/etc/docker/certs.d/{{front_hostname}}:5000/ca.crt"
      src: "/opt/docker_registry/certs/ca.crt"

  - name: Delete unneeded certificates
    file:
      path: "/opt/docker_registry/certs/{{item}}"
      state: absent
    with_items:
      - "{{front_hostname}}.csr"
      - client.key
      - ca.key

  - name: Run docker registry
    docker_container:
      name: registry
      image: registry:2
      volumes:
        - /opt/docker_registry:/var/lib/registry
        - /opt/docker_registry/certs:/certs
      ports:
       - "5000:5000"
      env:
          REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/{{front_hostname}}.cert"
          REGISTRY_HTTP_TLS_KEY: "/certs/{{front_hostname}}.key"
      restart_policy: always

  # Needed due to reconfiguration errors
  - name: Restart docker registry
    docker_container:
      state: started
      restart: yes
      name: registry
      image: registry:2
      volumes:
        - /opt/docker_registry:/var/lib/registry
        - /opt/docker_registry/certs:/certs
      ports:
       - "5000:5000"
      env:
          REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/{{front_hostname}}.cert"
          REGISTRY_HTTP_TLS_KEY: "/certs/{{front_hostname}}.key"
      restart_policy: always

  when: (docker_installation == "registry") or (docker_installation == "both")

###############################################################################################
## MIRROR
###############################################################################################

- block:
  - name: Create mirror directory
    file:
      path: "/opt/docker_registry/mirror"
      state: directory
      mode: 0755

  - name: Run docker mirror
    docker_container:
      name: mirror
      image: eubrabigsea/registry:2
      volumes:
        - "/opt/docker_registry/mirror/:/var/lib/registry/"
      ports:
       - "5555:5000"
      env:
          STORAGE_PATH: "/registry"
          STANDALONE: "false"
          MIRROR_SOURCE: "https:/registry-1.docker.io"
          MIRROR_SOURCE_INDEX: "https://index.docker.io"          
      restart_policy: always
     
  when: (docker_installation == "mirror") or (docker_installation == "both")