---
###############################################################################################
## REGISTRY
###############################################################################################
- block:
  - name: Create directory for registry keys
    file:
      path: "/etc/docker/certs.d/{{front_hostname}}:5000/"
      state: directory

  - name: Copy certificates from frontend
    copy: src="/opt/docker_registry/certs/{{item}}" dest="/opt/docker_registry/certs/"
    with_items:
      - "{{front_hostname}}.cert"
      - "{{front_hostname}}.key"

  - name: Copy Certificates from frontend-2
    copy: src="/opt/docker_registry/certs/{{item}}" dest="/etc/docker/certs.d/{{front_hostname}}:5000/"
    with_items:
      - "{{front_hostname}}.cert"
      - "{{front_hostname}}.key"
      - ca.crt

when: "{{ docker_installation }}" == "registry" or "{{ docker_installation }}" == "both"


###############################################################################################
## MIRROR
###############################################################################################
- block:
  - name: Create directory for registry keys
    file:
      path: "/etc/docker/certs.d/{{front_hostname}}:5000/"
      state: directory
      
when: "{{ docker_installation }}" == "mirror" or "{{ docker_installation }}" == "both"